# Generated by Django 4.2.13 on 2024-05-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('año', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
