# Generated by Django 4.2.13 on 2024-05-25 01:07

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web_automotora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='fecha',
            field=models.DateTimeField(default=datetime.date(2024, 5, 25)),
        ),
        migrations.AlterField(
            model_name='auto',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
