# Generated by Django 4.2.13 on 2024-05-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_automotora', '0003_alter_auto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
    ]
