# Generated by Django 4.2.13 on 2024-05-25 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_automotora', '0004_auto_comprado'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
