# Generated by Django 5.0.1 on 2024-05-25 13:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_automotora', '0005_auto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='static/subidas'),
        ),
    ]
