# Generated by Django 5.0.6 on 2024-05-29 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_automotora', '0006_tipo_alter_auto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='subidas/autos'),
        ),
    ]
