# Generated by Django 5.0.6 on 2024-05-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_automotora', '0007_alter_auto_fecha_alter_auto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='autos/'),
        ),
    ]
