# Generated by Django 4.2.13 on 2024-06-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='productos')),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
