# Generated by Django 4.2.13 on 2024-06-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_compra_detallecompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='direccion',
            field=models.CharField(max_length=1024),
        ),
    ]
