# Generated by Django 4.2.13 on 2024-06-08 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='completado',
            field=models.BooleanField(),
        ),
    ]
